remote_theme: just-the-docs/just-the-docs
title: Math Curriculum"
description: math Curriculum
color_scheme: dark
kramdown:
  math_engine: mathjax

callouts:
  definition:
    title: Definition
    color: green
  theorem:
    title: Theorem
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red